### ISSUE TITLE
Dapnetgateway stops working after few minutes

### ISSUE THREAD

**Issue by iw2gob** [g4klx/DAPNETGateway#12]
After last update, service stops working after few minutes. 
Maurizio IW2GOB

**Comment by dd5xl** [comment]
Issue is known and most likely caused by DoS countermeasures at the core server. As the root cause, persistent high-speed re-connects form DAPNETGateway clients has been just fixed, I expect these countermeasures to be removed soon.

**Comment by phl0** [comment]
Maurizio, sorry to say but it works as expected. We have a problem with people running DAPNETGateways without registered transmitters. I could not find your callsign in the transmitter list. That means your DAPNETGateway didn't even work before that fix. Go ahead and file a ticket to get a transmitter registered. Otherwise running DAPNETGateway is completely useless as those cannot connect to DAPNET.

**Comment by iw2gob** [comment]
Hi Florian, I have 2 transmitters registered on Italy network node1.dapnet-italia.it. I have just recompiled and it seems working. 73, Maurizio IW2GOB

**Comment by on2aav** [comment]
Tried a couple of times this morning, and no successfull Pocsag network connection. Apparently after one try to the DAPNETgateway, it does not try to re-connect any more. Should I keep on trying manually of just leave the Pocsag option in Pi-star ON ? 73 ON2ON (mmdvm/pistar)

**Comment by phl0** [comment]
@iw2gob I cannot help with the Italian node. I simply don't know if they have similar countermeasures in place to mitigate such a "DDoS attack".

@on2aav Have you updated your PiStar/DAPNETGateway? Otherwise please check if you are on the (temporary) blacklist: https://hampager.de/blocked-ips/

**Comment by lwkoon** [comment]
I encounter something which, the pistar will hang when sending certain strings
below are the string that send via POCSAG via pistar-dapnetapi via my bashscript

#!/bin/sh

METRIC=1 # 0 for F, 1 for C
#PLACE=Kuala+Lumpur
#PLACE=ShangHai
#PLACE=Manila
#PLACE=Moscow
#PLACE=toronto
#PLACE=Sydney
#PLACE=Oslo
#PLACE=Oymyakon
PLACE=Dudinka
CALLSIGN=9W2LWK

result1=`curl -s http://rss.accuweather.com/rss/liveweat ... e\=${PLACE} | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \L\1/p'`
result2=`echo ${result1} | sed 's/\xB0/ degree /g' `
result=`echo ${result2} | sed 's/[^[:print:]\t]//g' `

compare=`echo ${result} | grep -a --text thunderstorms`
if [[ ${compare} =~ .*thunderstorms.* ]]
then
word="${PLACE}, ${result} , Please bring umbrella"
echo $word
/usr/local/sbin/pistar-dapnetapi ${CALLSIGN} '${word}' debug"
else
word="${PLACE}, ${result} , Have a nice day"
echo $word
/usr/local/sbin/pistar-dapnetapi ${CALLSIGN} '${word}' debug"
fi

The MMDVM still alive, u still can ssh into it, but the MMDVM service is eventually hang. i need to power of and on it back again

but when u use other "PLACE=Kuala+Lumpur" for instance, the POCSAG go through... i wonder what's going on?

it confirm will hang on "PLACE=Dudinka" , "PLACE=Oslo", "PLACE=Moscow" and "PLACE=Sydney"

anyone wanna try on their pistar?
