### ISSUE TITLE
Check for whitespaces in Callsign and AuthKey

### ISSUE THREAD

**Issue by dh3wr** [g4klx/DAPNETGateway#15]
Maybe from C&P, we have some candidates trying to login with
"DL1ABC "

The welcome line has to pass this test.
``private static final Pattern AUTH_PATTERN = Pattern.compile("\\[([/\\-\\p{Alnum}]+) v(\\d[\\d\\.]+[\\p{Graph}]*) ([\\p{Alnum}_]+) (\\p{Alnum}+)\\]");``

So there are no whitespaces in neither the callsign nor the AuthKey. Please filter them on the Client site, when you read from the config.

**Comment by phl0** [comment]
Implemented with https://github.com/g4klx/DAPNETGateway/commit/5a9e3a4a66e8ed455607bb9b183a20e380525c95
