### ISSUE TITLE
Callsign for DAPNET login is sent always in uppercase

### ISSUE THREAD

**Issue by dh3wr** [g4klx/DAPNETGateway#16]
According to user feedback from DK1LJ, the callsign for DAPNET login is always converted to uppercase. This is against the DAPNET convention, where no upper/lowercase conversion should be done and if it should be necessary for some reason, it should be lowercase.
Maybe this is a pi* image web configuration automatism issue?

**Comment by phl0** [comment]
Closed with https://github.com/g4klx/DAPNETGateway/commit/6b4d5d5fee3def6ac6ba630ae5858e12767dbc8b
