### ISSUE TITLE
Cannot open the DAPNET network port

### ISSUE THREAD

**Issue by ravny** [g4klx/DAPNETGateway#4]
I opened port 4800 udp but Im getting error message that can not opened network port.

M: 2018-07-07 05:03:06.008 Opening POCSAG network connection
I: 2018-07-07 05:03:06.011 Opening UDP port on 4800
M: 2018-07-07 05:03:06.014 Opening DAPNET connection
E: 2018-07-07 05:05:19.157 Cannot connect the TCP client socket, err=110
M: 2018-07-07 05:05:19.157 Closing POCSAG network connection
E: 2018-07-07 05:05:19.157 Cannot open the DAPNET network port

**Comment by ItTakesTwo** [comment]
That error message refers to the connection to the DAPNET server, not the local connection between DAPNETGateway and e.g. MMDVMHost. Check if the DAPNET server you are trying to connect to is online or if the connection is blocked somewhere inside your network.

**Comment by phl0** [comment]
Show your config (without passwords) please.

**Comment by ravny** [comment]
[General]
Callsign=s56iar
RptAddress=127.0.0.1
RptPort=3800
LocalAddress=127.0.0.1
LocalPort=4800
Daemon=1

[Log]
DisplayLevel=0
FileLevel=1
FilePath=/var/log/pi-star
FileRoot=DAPNETGateway

[DAPNET]
Address=dapnet.afu.rwth-aachen.de
Port=43434
AuthKey=mysecretkey
SuppressTimeWhenBusy=1
Debug=1

**Comment by phl0** [comment]
Can you ping dapnet.afu.rwth-aachen.de?

**Comment by ravny** [comment]
Yes I can ping and also I could not find my call sign under Transmitters

**Comment by phl0** [comment]
Okay, then it is not a problem of DAPNETGateway. You need to register your transmitter. See https://support.hampager.de

**Comment by ravny** [comment]
I already have registered my transmitter but still san not see it under transmitetr on the web. I will open a ticket with question.

**Comment by phl0** [comment]
Where and how did you register your transmitter?

**Comment by ravny** [comment]
Dear Matej,
your transmitter is the first dapnet pocsag site in Slovenia!

The account for the transmitter has been created. Login data for UniPager is:
Callsign: s56iar
AuthKey: XXXXXXX

The transmitter has been added to the following groups: all, s5-all
Active time slots are: All (private hotspot)

Vy73 Johannes
DAPNET-Support-Team 
Your DAPNET Support Desk Team,

**Comment by phl0** [comment]
I will lookup the ticket and re-create your transmitter. QRX.

**Comment by phl0** [comment]
Transmitter was re-created. Pls test.

**Comment by ravny** [comment]
NOW is working TNX for your help ;)

**Comment by sysadminpower2019** [comment]
@phl0 I have the same issue here. Would you please recreate my transmitter as well?

**Comment by phl0** [comment]
> @phl0 I have the same issue here. Would you please recreate my transmitter as well?

Whats the callsign pls?

**Comment by mattfox27** [comment]
I have this same error k06dsb
